// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj2fWWTnY9hLeJw_D7WjsuNzRIwP0IXOA',
    appId: '1:718144914327:web:92cb5bb9c28f6b21da7ad2',
    messagingSenderId: '718144914327',
    projectId: 'bayito-1b5b8',
    authDomain: 'bayito-1b5b8.firebaseapp.com',
    storageBucket: 'bayito-1b5b8.firebasestorage.app',
    measurementId: 'G-1JQDDHNV9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnRrOjeoW-hbG7vm9T-g5JSyzvsaYvyrA',
    appId: '1:718144914327:android:5cf77874ee44d0d8da7ad2',
    messagingSenderId: '718144914327',
    projectId: 'bayito-1b5b8',
    storageBucket: 'bayito-1b5b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv3QehlPK2xVxGgzTpJDqEHLjhARr1Ysg',
    appId: '1:718144914327:ios:054203b28c3f8934da7ad2',
    messagingSenderId: '718144914327',
    projectId: 'bayito-1b5b8',
    storageBucket: 'bayito-1b5b8.firebasestorage.app',
    iosBundleId: 'com.bayito.user.bayitouser',
  );
}
